config/routes.rb
Rails.application.routes.draw do
  resources :restaurants, except: [:edit, :destroy] do
    member do
      post 'upvote'
      post 'downvote'
    end
  end

end

app/models/downvote.rb
class Downvote < ActiveRecord::Base
  belongs_to :restaurant
end

app/models/restaurant.rb
class Restaurant < ActiveRecord::Base
  has_many :votes, dependent: :destroy
  has_many :downvotes, dependent: :destroy

  def self.search(search)
    where('name LIKE ? OR location LIKE ?', "%#{search}%", "%#{search}%")
  end
end

app/models/vote.rb
class Vote < ActiveRecord::Base
  belongs_to :restaurant
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/restaurants_controller.rb
class RestaurantsController < ApplicationController
  before_action :set_restaurant, only: [:show, :edit, :update, :destroy]

  # GET /restaurants
  # GET /restaurants.json
  def index
    if params[:search]
      @restaurants = Restaurant.search(params[:search])
    else
      @restaurants = Restaurant.all
    end
  end

  # GET /restaurants/1
  # GET /restaurants/1.json
  def show
  end

  # GET /restaurants/new
  def new
    @restaurant = Restaurant.new
  end

  # GET /restaurants/1/edit
  def edit
  end

  # POST /restaurants
  # POST /restaurants.json
  def create
    @restaurant = Restaurant.new(restaurant_params)

    respond_to do |format|
      if @restaurant.save
        format.html { redirect_to @restaurant, notice: 'Restaurant was successfully created.' }
        format.json { render :show, status: :created, location: @restaurant }
      else
        format.html { render :new }
        format.json { render json: @restaurant.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /restaurants/1
  # PATCH/PUT /restaurants/1.json
  def update
    respond_to do |format|
      if @restaurant.update(restaurant_params)
        format.html { redirect_to @restaurant, notice: 'Restaurant was successfully updated.' }
        format.json { render :show, status: :ok, location: @restaurant }
      else
        format.html { render :edit }
        format.json { render json: @restaurant.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /restaurants/1
  # DELETE /restaurants/1.json
  def destroy
    @restaurant.destroy
    respond_to do |format|
      format.html { redirect_to restaurants_url, notice: 'Restaurant was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  # UPVOTE /restaurants/1
  # UPVOTE /restaurants/1.json
  def upvote
    @restaurant = Restaurant.find(params[:id])
    @restaurant.votes.create
    respond_to do |format|
      format.html { redirect_to @restaurant, notice: 'Up Vote successful' }
      format.json { render :show, status: :ok, location: @restaurant }
    end
  end

  # DOWNVOTE /restaurants/1
  # DOWNVOTE /restaurants/1.json
  def downvote
    @restaurant = Restaurant.find(params[:id])
    @restaurant.downvotes.create
    respond_to do |format|
      format.html { redirect_to @restaurant, notice: 'Down Vote successful' }
      format.json { render :show, status: :ok, location: @restaurant }
    end
  end
  

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_restaurant
      @restaurant = Restaurant.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def restaurant_params
      params.require(:restaurant).permit(:name, :location, :up_votes, :down_votes)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/restaurants_helper.rb
module RestaurantsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Splitthecheck</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<div id="search">
  <%= render :partial => 'restaurants/search' %>
</div>
<%= yield %>

</body>
</html>

app/views/restaurants/_form.html.erb
<%= form_for(@restaurant) do |f| %>
  <% if @restaurant.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@restaurant.errors.count, "error") %> prohibited this restaurant from being saved:</h2>

      <ul>
      <% @restaurant.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :location %><br>
    <%= f.text_field :location %>
  </div>
  <div class="field">
    <%= f.label :up_votes %><br>
    <%= f.number_field :up_votes %>
  </div>
  <div class="field">
    <%= f.label :down_votes %><br>
    <%= f.number_field :down_votes %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/restaurants/_search.html.erb
<%= form_tag restaurants_path, :method => 'get' do %>
  <p>
    <%= text_field_tag :search, params[:search], id: "search_field" %>
    <%= submit_tag "Search", :name => nil %>
  </p>
<% end %>

<% if @restaurants.blank? %>
  <h3>There are no restaurants containing the term <%= params[:search] %></h3>
<% end %>

app/views/restaurants/edit.html.erb
<h1>Editing Restaurant</h1>

<%= render 'form' %>

<%= link_to 'Show', @restaurant %> |
<%= link_to 'Back', restaurants_path %>

app/views/restaurants/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Restaurants</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Location</th>
      <th>Up votes</th>
      <th>Down votes</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @restaurants.each do |restaurant| %>
      <tr>
        <td><%= restaurant.name %></td>
        <td><%= restaurant.location %></td>
        <td><%= restaurant.votes.count %></td>
        <td><%= restaurant.downvotes.count %></td>
        <td><%= link_to 'Show', restaurant %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Restaurant', new_restaurant_path %>

app/views/restaurants/new.html.erb
<h1>New Restaurant</h1>

<%= render 'form' %>

<%= link_to 'Back', restaurants_path %>

app/views/restaurants/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @restaurant.name %>
</p>

<p>
  <strong>Location:</strong>
  <%= @restaurant.location %>
</p>

<p>
  <strong>Up votes:</strong>
  <%= @restaurant.votes.count %>
  <%= button_to 'Up Vote', upvote_restaurant_path(@restaurant), method: :post %></td>
</p>

<p>
  <strong>Down votes:</strong>
  <%= @restaurant.downvotes.count %>
  <%= button_to 'Down Vote', downvote_restaurant_path(@restaurant), method: :post %></td>
</p>

<%= link_to 'Back', restaurants_path %>